config/routes.rb
PlewDev1::Application.routes.draw do

  resources :vids

  get "portfolio" => "home#portfolio", :as => :portfolio
  

  match "/:section/fotografia-autorska" => "front_section#auth_gallery_categories", :as => :auth_gallery_categories
  match "/:section/fotografia-autorska/:cat" => "front_section#auth_gallery", :as => :auth_gallery
  match "/:section/fotografia-autorska/:cat/:id" => "front_section#auth_gallery", :as => :auth_gallery_specific

  match "/:section/fotografia-komercyjna" => "front_section#com_gallery_categories", :as => :com_gallery_categories
  match "/:section/fotografia-komercyjna/:cat" => "front_section#com_gallery", :as => :com_gallery
  match "/:section/fotografia-komercyjna/:cat/:id" => "front_section#com_gallery", :as => :com_gallery_specific

  match "/:section/video" => "front_section#vid", :as => :front_vid
  match "/:section/video/:id" => "front_section#single_vid", :as => :front_vid_single
  match "/:section/info" => "front_section#info", :as => :info
  match "/:section/recenzja/:id" => "front_section#review", :as => :front_review

  match 'zmien-jezyk/:locale' => 'application#set_locale', :as => :set_language
  match 'zmien-uzytkownika/:section' => 'admin#set_section', :as => :set_section
  
  get "home/index"

  match "admin" => "admin#index", :as => :admin
  match "admin/login" => "admin#login", :as => :admin_login
  match "admin/enter" => "admin#enter", :as => :admin_enter
  match "admin/logout" => "admin#logout", :as => :admin_logout

  match "galeria/:type" => "galleries#set_gallery_type", :as => :set_gallery_type
  match "sortuj-galerie/:id" => "galleries#sort", :as => :sort_gallery
  resources :galleries
  
  resources :pages

  root :to => 'home#index'
  

end

app/models/vid.rb
class Vid < ActiveRecord::Base
  attr_protected :id
  
  translates :title, :description

  class Translation
    attr_accessible :locale
  end
end

app/controllers/vids_controller.rb
class VidsController < AdminController


  def index
    @vids = Vid.all
  end


  def show
    @vid = Vid.find(params[:id])
  end


  def new
    @vid = Vid.new
  end


  def edit
    @vid = Vid.find(params[:id])
  end


  def create
    @vid = Vid.new(params[:vid])
    
    if @vid.save
      redirect_to vids_url, notice: 'Video dodane.'
    else
      render action: "new"
    end
  end
  

  def update
    @vid = Vid.find(params[:id])
    
    if @vid.update_attributes(params[:vid])
      redirect_to vids_url, notice: 'Video wyedytowane.'
    else
      render action: "edit"
    end
  end
  
  
  def destroy
    @vid = Vid.find(params[:id])
    @vid.destroy
    
    redirect_to vids_url
  end
end

app/helpers/vids_helper.rb
module VidsHelper
end

app/views/vids/_form.html.erb
<%= form_for(@vid) do |f| %>
  <% if @vid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vid.errors.count, "error") %> prohibited this vid from being saved:</h2>

      <ul>
      <% @vid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Tytuł" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, "Opis" %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link_to_vid, "Link do video" %><br />
    <%= f.text_area :link_to_vid, :style => "height: 80px;" %>
  </div>
  <div class="actions">
    <%= f.submit 'Zapisz' %>
  </div>
<% end %>

app/views/vids/edit.html.erb
<h1>Editing vid</h1>

<%= render 'form' %>

<%= link_to 'Show', @vid %> |
<%= link_to 'Back', vids_path %>

app/views/vids/index.html.erb
<h1>Video</h1>
<%= link_to 'Dodaj nowe video', new_vid_path %>
<br/>
<br/>
<br/>
<table width="100%">
  <tr>
    <th width="30%">Tytuł</th>
    <th width="60%">Opis</th>
    <th width="10%">Link</th>
  </tr>

<% @vids.each do |vid| %>
  <tr>
    <td><%= vid.title %></td>
    <td><%= vid.description %></td>
    <td><%= vid.link_to_vid %></td>
    <td><%= link_to 'Edytuj', edit_vid_path(vid) %> <%= link_to 'Usuń', vid, confirm: 'Czy na pewno chcesz usunąć video? ', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/vids/new.html.erb
<h1>New vid</h1>

<%= render 'form' %>

<%= link_to 'Back', vids_path %>

app/views/vids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Section:</b>
  <%= @vid.section %>
</p>

<p>
  <b>Title:</b>
  <%= @vid.title %>
</p>

<p>
  <b>Description:</b>
  <%= @vid.description %>
</p>

<p>
  <b>Link to vid:</b>
  <%= @vid.link_to_vid %>
</p>


<%= link_to 'Edit', edit_vid_path(@vid) %> |
<%= link_to 'Back', vids_path %>