config/routes.rb
PlewDev1::Application.routes.draw do

  resources :vids

  get "portfolio" => "home#portfolio", :as => :portfolio
  

  match "/:section/fotografia-autorska" => "front_section#auth_gallery_categories", :as => :auth_gallery_categories
  match "/:section/fotografia-autorska/:cat" => "front_section#auth_gallery", :as => :auth_gallery
  match "/:section/fotografia-autorska/:cat/:id" => "front_section#auth_gallery", :as => :auth_gallery_specific

  match "/:section/fotografia-komercyjna" => "front_section#com_gallery_categories", :as => :com_gallery_categories
  match "/:section/fotografia-komercyjna/:cat" => "front_section#com_gallery", :as => :com_gallery
  match "/:section/fotografia-komercyjna/:cat/:id" => "front_section#com_gallery", :as => :com_gallery_specific

  match "/:section/video" => "front_section#vid", :as => :front_vid
  match "/:section/video/:id" => "front_section#single_vid", :as => :front_vid_single
  match "/:section/info" => "front_section#info", :as => :info
  match "/:section/recenzja/:id" => "front_section#review", :as => :front_review

  match 'zmien-jezyk/:locale' => 'application#set_locale', :as => :set_language
  match 'zmien-uzytkownika/:section' => 'admin#set_section', :as => :set_section
  
  get "home/index"

  match "admin" => "admin#index", :as => :admin
  match "admin/login" => "admin#login", :as => :admin_login
  match "admin/enter" => "admin#enter", :as => :admin_enter
  match "admin/logout" => "admin#logout", :as => :admin_logout

  match "galeria/:type" => "galleries#set_gallery_type", :as => :set_gallery_type
  match "sortuj-galerie/:id" => "galleries#sort", :as => :sort_gallery
  resources :galleries
  
  resources :pages

  root :to => 'home#index'
  

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_protected :id
  
  translates :title, :description
  
  has_many :photos, :dependent => :destroy
  accepts_nested_attributes_for :photos, :reject_if => lambda { |a| a[:photo].blank? && a[:p_title].blank? }, :allow_destroy => true
  
  class Translation
    attr_accessible :locale
  end

  mount_uploader :icon, IconUploader


  def sorted_photos
      photos = Photo.where(:gallery_id => self.id).order("position ASC")
      return photos
  end
end

app/controllers/galleries_controller.rb
# -*- encoding: utf-8 -*-
class GalleriesController < AdminController


  def sort
    @gallery = Gallery.find(params[:id])
    if @gallery.present?
      @photos = Photo.where(:gallery_id => @gallery.id).order("position ASC")
    else
      @photos = []
    end

    @photos.each do |photo|
      photo.position = params['ph_li'].index(photo.id.to_s) + 1
      photo.save 
    end

    render :nothing => true
  end

  
  def set_gallery_type
    if params[:type].present?
      session[:type] = params[:type]
      redirect_to galleries_url
    else
      admin_url
    end
  end


  def index
    @galleries = Gallery.where(:section => session[:section], :gal_type => session[:type])
  end


  def show
    @gallery = Gallery.find_by_id(params[:id])
    if @gallery.present?
      @photos = Photo.where(:gallery_id => @gallery.id).order("position ASC")
    else
      @photos = []
    end
  end


  def new
    @gallery = Gallery.new
  end


  def edit
    @gallery = Gallery.find(params[:id])
  end


  def create
    @gallery = Gallery.new(params[:gallery])
    @gallery.section = session[:section]
    @gallery.gal_type = session[:type]
    
    if @gallery.save
      redirect_to galleries_url, notice: 'Galeria utworzona.'
    else
      render action: "new"
    end
  end

  
  def update
    @gallery = Gallery.find(params[:id])
    
    if @gallery.update_attributes(params[:gallery])
      redirect_to galleries_url, notice: 'Galeria wyedytowana.'
    else
      render action: "edit"
    end
  end
  
  
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    
    redirect_to galleries_url
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery, :html => {:multipart => true }) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>
      
      <ul>
	<% @gallery.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>
  

  <% if session[:section] == SECTION[0] %>
    <div class="field">
      <%= f.label :label, "Kategoria" %>
      <% if session[:type] == GAL_TYPE[0] %>
        <%= f.select :label, options_for_select(CATEGORIES1A, @gallery.label) %>
      <% else %>
        <%= f.select :label, options_for_select(CATEGORIES1B, @gallery.label) %>
      <% end %>
    </div>
  <% elsif session[:section] == SECTION[1] %>
  <% else %>
    <div class="field">
      <%= f.label :label, "Wskaż ikonę" %>
      <%= f.file_field :icon %>
      <%= image_tag(@gallery.icon.thumb.url) if @gallery.icon.present? %>

      <%#= f.label :label, "Kategoria" %>
      <%#= f.select :label, options_for_select(CATEGORIES2, @gallery.label) %>
    </div>
  <% end %>
    
  <div class="field">
    <%= f.label :title, "Tytuł Albumu" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, "Opis Albumu" %>
    <%= f.text_area :description %>
  </div>
  
  <%= f.fields_for :photos do |builder| %>
    <%= render "photo_fields", :f => builder %>
  <% end %>  
  <p><%= link_to_add_fields "Dodaj zdjęcie", f, :photos %></p>
  
  <div class="actions">
    <%= f.submit 'Zapisz' %>
  </div><br>
<% end %>

app/views/galleries/_photo_fields.html.erb
<div class="field">
  <%= f.label :p_title, "Tytuł zdjęcia" %>
  <%= f.text_field :p_title %>
</div>
<div class="field">
  <%= f.label :photo, "Plik" %>

  <%= f.file_field :photo %>
  <%= f.hidden_field :photo_cache %>

  <%= link_to_remove_fields "usuń", f %><br>
  <% if f.object.photo.present? %>
    <br /><%= (image_tag f.object.photo.thumb.url) %><br>
  <% end %><br>
  --------------------------------------<br>
</div>

app/views/galleries/edit.html.erb
<h1>Edytuj Album <%= (disp = show_gal_type(session[:section], session[:type])).present? ? '- '+disp : '' %></h1>

<%= render 'form' %>

<%= link_to 'Wróć do panelu', galleries_path %>

app/views/galleries/index.html.erb
<h1>Albumy zdjęć <%= (disp = show_gal_type(session[:section], session[:type])).present? ? '- '+disp : '' %></h1>
<%= link_to 'Dodaj nowy album', new_gallery_path %>
<br/>
<br/>
<br/>
<table width="100%">
  <tr>
    <th width="20%">Tytuł</th>
    <th width="60%">Zdjęcia</th>
    <th width="20%">Opcje</th>
  </tr>

  <% @galleries.each do |gallery| %>
    <tr>
      <td><%= gallery.title %> <%= image_tag(gallery.icon.thumb.url) if gallery.icon.present? %></td>
      <td>
        <% gallery.sorted_photos.each do |photo| %>
          <% if photo.photo.present? %>
            <%= image_tag photo.photo.thumb.url, :title => photo.p_title, :alt => photo.p_title %>
          <% else %>
            Photo error
          <% end %>
        <% end %>
      </td>
      <td>
        <%= link_to 'Sortuj', gallery_path(gallery) %>
        <%= link_to 'Edytuj', edit_gallery_path(gallery) %> 
        <%= link_to 'Usuń', gallery, confirm: 'Czy na pewno chcesz usunąć galerię? ', method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/galleries/new.html.erb
<h1>Nowy Album <%= (disp = show_gal_type(session[:section], session[:type])).present? ? '- '+disp : '' %></h1>

<%= render 'form' %>
<div class="clearspace"></div>
<%= link_to 'Anuluj', galleries_path %>
<div class="clearspace"></div>

app/views/galleries/show.html.erb
<h1>Galeria <%= (disp = show_gal_type(session[:section], session[:type])).present? ? '- '+disp : '' %></h1>

<p>
	<b>Tytuł Albumu:</b>
	<%= @gallery.title %>
</p>

<b>Zdjęcia:</b> złap zdjęcie i przesuń<br/>
<ol id="ph_uls">
  <% @photos.each do |photo| %>
  <li class="ph_ul" id="ph_li_<%= photo.id %>">
    <span class="handle">    
      <%= image_tag photo.photo.thumb.url %>
    </span>
  </li>
  <% end %>
</ol>

<div class="clearspace"></div>
<%= link_to 'Edytuj album', edit_gallery_path(@gallery) %> |
<%= link_to 'Zapisz', galleries_path %>


<style type="text/css">
  .handle:hover{cursor: move;}
</style>

<% content_for :javascript do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
      $('#ph_uls').sortable({
        axis: 'x',
        dropOnEmpty: false,
        handle: '.handle',
        cursor: 'crosshair',
        items: 'li',
        opacity: 0.4,
        scroll: true,
        update: function(){
          $.ajax({
            type: 'post',
            data: $('#ph_uls').sortable('serialize'),
            dataType: 'script',
            complete: function(request){
              $('#books').effect('highlight');
            },
            url: '<%= sort_gallery_url(@gallery) %>'
          })
        }
      });
    });
  <% end %>
<% end %>