config/routes.rb
PlewDev1::Application.routes.draw do

  resources :vids

  get "portfolio" => "home#portfolio", :as => :portfolio
  

  match "/:section/fotografia-autorska" => "front_section#auth_gallery_categories", :as => :auth_gallery_categories
  match "/:section/fotografia-autorska/:cat" => "front_section#auth_gallery", :as => :auth_gallery
  match "/:section/fotografia-autorska/:cat/:id" => "front_section#auth_gallery", :as => :auth_gallery_specific

  match "/:section/fotografia-komercyjna" => "front_section#com_gallery_categories", :as => :com_gallery_categories
  match "/:section/fotografia-komercyjna/:cat" => "front_section#com_gallery", :as => :com_gallery
  match "/:section/fotografia-komercyjna/:cat/:id" => "front_section#com_gallery", :as => :com_gallery_specific

  match "/:section/video" => "front_section#vid", :as => :front_vid
  match "/:section/video/:id" => "front_section#single_vid", :as => :front_vid_single
  match "/:section/info" => "front_section#info", :as => :info
  match "/:section/recenzja/:id" => "front_section#review", :as => :front_review

  match 'zmien-jezyk/:locale' => 'application#set_locale', :as => :set_language
  match 'zmien-uzytkownika/:section' => 'admin#set_section', :as => :set_section
  
  get "home/index"

  match "admin" => "admin#index", :as => :admin
  match "admin/login" => "admin#login", :as => :admin_login
  match "admin/enter" => "admin#enter", :as => :admin_enter
  match "admin/logout" => "admin#logout", :as => :admin_logout

  match "galeria/:type" => "galleries#set_gallery_type", :as => :set_gallery_type
  match "sortuj-galerie/:id" => "galleries#sort", :as => :sort_gallery
  resources :galleries
  
  resources :pages

  root :to => 'home#index'
  

end

app/controllers/front_section_controller.rb
class FrontSectionController < ApplicationController

  def auth_gallery_categories
    if params[:section].present?      
      if (params[:section] == SECTION[1]) || (params[:section] == SECTION[2])
        redirect_to auth_gallery_url(:section => params[:section], :cat => 'wszystkie')
      else
        categories = Gallery.where(["section = '#{params[:section]}' AND gal_type = '#{GAL_TYPE[0]}' AND label IS NOT NULL"])
        if categories.present?
          @categories = categories.collect.collect{|g| g.label}.uniq
        else
          @categories = []
        end        
      end
    else
      redirect_to root_url
    end    
  end


  def auth_gallery
    if params[:section].present?
      if params[:cat].present? && params[:cat] != 'wszystkie'
        @galleries = Gallery.where(:section => params[:section], :gal_type => GAL_TYPE[0], :label => params[:cat])
      else
        @galleries = Gallery.where(:section => params[:section], :gal_type => GAL_TYPE[0])
      end
      
      if params[:id].present?
        @selected_gallery = Gallery.find_by_id(params[:id])
      else
        @selected_gallery = @galleries.first
      end
    else
      redirect_to root_url
    end    
  end


  def com_gallery_categories
    if params[:section].present?      
      if params[:section] == SECTION[1]
        redirect_to com_gallery_url(:section => params[:section], :cat => 'wszystkie')
      else
        categories = Gallery.where(["section = '#{params[:section]}' AND gal_type = '#{GAL_TYPE[1]}' AND label IS NOT NULL"])
        if categories.present?
          @categories = categories.collect.collect{|g| g.label}.uniq
        else
          @categories = []
        end
      end     
    else
      redirect_to root_url
    end    
  end

  
  def com_gallery
    if params[:section].present?
      if params[:cat].present? && params[:cat] != 'wszystkie'
        @galleries = Gallery.where(:section => params[:section], :gal_type => GAL_TYPE[1], :label => params[:cat])
      else
        @galleries = Gallery.where(:section => params[:section], :gal_type => GAL_TYPE[1])
      end
      
      if params[:id].present?
        @selected_gallery = Gallery.find_by_id(params[:id])
      else
        @selected_gallery = @galleries.first
      end
    else
      redirect_to root_url
    end    
  end

  
  def vid
    if params[:section].present?      
      @vids = Vid.all
      
      if params[:id].present?
        @selected_vid = Vid.find_by_id(params[:id])
      else
        @selected_vid = @vids.first
      end
    else
      redirect_to root_url
    end
  end

  
  def info
    if params[:section].present?      
      @reviews = Page.where(:section => params[:section], :label => PAGE_LABELS[0][1]).order("created_at DESC")
      @contact = Page.where(:section => params[:section], :label => PAGE_LABELS[1][1]).first      
    else
      redirect_to root_url
    end
  end


  def review
    @review = Page.find(params[:id])    
  end
end

app/helpers/front_section_helper.rb
module FrontSectionHelper
end

app/views/front_section/auth_gallery.html.erb
<div class="gallery-holder">  
  <div class="left-gal">    
    <div class="category-holder">
      <% if params[:section] == SECTION[0] %>
        <%= link_to t('main.return'), auth_gallery_categories_url(:section => params[:section]) %><br/><br/>
      <% end %>

      <p><%= t('main.category') %>:</p>
      <ul>	
        <% @galleries.each do |gallery| %>
          
          <% if params[:section] == SECTION[2] %>
            <li>
              <% if params[:cat].present? %>
                <%= link_to image_tag(gallery.icon.main.url, :alt => gallery.title), auth_gallery_specific_url(:section => params[:section], :cat => params[:cat], :id => gallery) %>
              <% else %>
                <%= link_to gallery.title, auth_gallery_specific_url(:section => params[:section], :id => gallery) %>
              <% end %>
            </li>
          <% else %>
            <li>
              <% if params[:cat].present? %>
                <%= link_to gallery.title, auth_gallery_specific_url(:section => params[:section], :cat => params[:cat], :id => gallery) %>
              <% else %>
                <%= link_to gallery.title, auth_gallery_specific_url(:section => params[:section], :id => gallery) %>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="right-gal">
    <div class="right-col">
      <% if @selected_gallery.present? %>
      <div class="clear album-desc">
        <%= @selected_gallery.description %>
      </div>

      <div id="slides">
        <div class="slides_container">
          <% @selected_gallery.sorted_photos.each do |photo| %>
          <div>
            <p class="photo-title"><%= photo.p_title %></p>
            <%= link_to(image_tag(photo.photo.main.url), photo.photo.url, :class => "gallery") %>
          </div>
          <% end %>
        </div><br>
        <ul class="pagination">
          <% @selected_gallery.sorted_photos.each do |photo| %>
          <li class="nivo-thumbs-enabled"><a href="#"><%= image_tag(photo.photo.small.url) %></a></li>
          <% end %>
        </ul>
      </div>
      <script>
      jQuery('a.gallery').colorbox({
        maxWidth: '90%',
        maxHeight: '90%'
      });
      </script>	 

      <% end %>
    </div>
  </div>
</div>


<% if false %>
<div class="slider-wrapper">
 <div id="slider" class="nivoSlider">
   <% @selected_gallery.photos.each do |photo| %>
   <%= link_to( image_tag(photo.photo.url, 'data-thumb' => photo.photo.small.url, :alt => '', :title => "#caption_#{photo.id}"), photo.photo.url, :class => "gallery") %>
   <% end %>
 </div><!-- odpalacz coloboxa wewnatrz nivoslidera, musi być tu -->
 <script>
 jQuery('a.gallery').colorbox({
   maxWidth: '90%',
   maxHeight: '90%'
 });
 </script>	  
</div>
<% end %>

app/views/front_section/auth_gallery_categories.html.erb
<div class="gallery-holder">  
  <div class="left-gal">    
    <div class="category-holder">
      <p><%= t('main.main_category') %>:</p>

      <ul>
	<% @categories.each do |c| %>
	  <li>
            <%= link_to show_category(c), auth_gallery_url(:section => params[:section], :cat => c) %>
	  </li>
	<% end %>
      </ul>
    </div>
  </div>
  <div class="right-gal">
    <div class="right-col">
     <% if params[:section] == SECTION[0] %>
    <div class="clearspace"></div>
		<%= image_tag('main-wojciech.png') %>
	<% end %>
    </div>
  </div>
</div>

app/views/front_section/com_gallery.html.erb
<div class="gallery-holder">
	<div class="left-gal">
    <div class="category-holder">
      <p><%= t('main.category') %>:</p>
      <ul>
       <% @galleries.each do |gallery| %>
       <li><%= link_to gallery.title, com_gallery_specific_url(:section => params[:section], :id => gallery) %></li>
       <% end %>	
      </ul>
    </div>
  </div>
  <div class="right-gal">

    <div class="right-col">
      <% if @selected_gallery.present? %>
        <div class="clear album-desc">
          <%= @selected_gallery.description %>
        </div>

        <div id="slides">
          <div class="slides_container">
            <% @selected_gallery.sorted_photos.each do |photo| %>
              <div>
                <p class="photo-title"><%= photo.p_title %></p>
                <%= link_to(image_tag(photo.photo.main.url), photo.photo.url, :class => "gallery") %>
              </div>
            <% end %>
          </div><br>
          <ul class="pagination">
            <% @selected_gallery.sorted_photos.each do |photo| %>
              <li class="nivo-thumbs-enabled"><a href="#"><%= image_tag(photo.photo.small.url) %></a></li>
            <% end %>
          </ul>
        </div>
        <script>
          jQuery('a.gallery').colorbox({
            maxWidth: '90%',
            maxHeight: '90%'
          });
        </script>	 
      <% end %>
    </div>
  </div>
</div>

app/views/front_section/com_gallery_categories.html.erb
<div class="gallery-holder">  
  <div class="left-gal">    
    <div class="category-holder">
      <p><%= t('main.main_category') %>:</p>

      <ul>
	<% @categories.each do |c| %>
	  <li>
            <%= link_to show_category(c), com_gallery_url(:section => params[:section], :cat => c) %>
	  </li>
	<% end %>
      </ul>
    </div>
  </div>
  <div class="right-gal">
    <div class="right-col">
    <% if params[:section] == SECTION[0] %>
		<div class="clearspace"></div>
		<%= image_tag('main-wojciech.png') %>
	<% end %>
    </div>
  </div>
</div>

app/views/front_section/info.html.erb
<div id="tabs">
  <ul>
    <li class="tabbed"><a href="#tab-1"><%= t('main.review_label') %></a></li>
    <li class="tabbed"><a href="#tab-2"><%= t('main.contact_label') %></a></li>
  </ul>
  <p class="clear"></p>
  <div id="tab-1" class="review-area">
    <% @reviews.each do |review| %>
      <%= link_to front_review_url(params[:section], review) do %>
        <span class="pub-date"><%= review.rev_date.strftime("%Y.%m.%d") if review.rev_date.present? %></span><br>
        <h6><%= review.title %></h6>
        <%= raw truncate(strip_tags(review.content), :length => 350) %><br><br>
        <span class="pub-read">Czytaj więcej »</span>
      <% end %>
      <p class="clear"><br></p>
      <br/>
    <% end %>
  </div>
  <div id="tab-2">
    <%= (image_tag @contact.photo.small.url) if @contact.present? && @contact.photo.present? %>
    <%= raw @contact.content if @contact.present? %>
    <p class="clear"></p>
  </div>   
</div>

app/views/front_section/review.html.erb
<div id="tabs">
	<ul>
    <li class="tabbed"><a href="../info#tab-1"><%= t('main.return') %></a></li>
    </ul>
    <p class="clear"></p>
	<div id="tab-1" class="review">
	<% if @review.present? %>
		<span class="pub-date"><%= @review.rev_date.strftime("%Y.%m.%d") if @review.rev_date.present? %> </span>
		<h6><%= @review.title %></h6>
		<%= raw @review.content %><br/>
	<% end %>
		<br/>
		
	</div>
</div>

app/views/front_section/vid.html.erb
<div class="gallery-holder">
<div class="clearspace"></div>
  <% @vids.each do |vid| %>
    <p class="vid-title"><%= vid.title %></p>
    <p class="vid-desc"><%= vid.description %></p><br/>
    <div class="video-holder"><%= raw vid.link_to_vid %>
		<br/><br/><div class="clear seperator"></div>
    </div>
    <div class="clearspace"></div>

  <% end %>
  
</div>