config/routes.rb
PlewDev1::Application.routes.draw do

  resources :vids

  get "portfolio" => "home#portfolio", :as => :portfolio
  

  match "/:section/fotografia-autorska" => "front_section#auth_gallery_categories", :as => :auth_gallery_categories
  match "/:section/fotografia-autorska/:cat" => "front_section#auth_gallery", :as => :auth_gallery
  match "/:section/fotografia-autorska/:cat/:id" => "front_section#auth_gallery", :as => :auth_gallery_specific

  match "/:section/fotografia-komercyjna" => "front_section#com_gallery_categories", :as => :com_gallery_categories
  match "/:section/fotografia-komercyjna/:cat" => "front_section#com_gallery", :as => :com_gallery
  match "/:section/fotografia-komercyjna/:cat/:id" => "front_section#com_gallery", :as => :com_gallery_specific

  match "/:section/video" => "front_section#vid", :as => :front_vid
  match "/:section/video/:id" => "front_section#single_vid", :as => :front_vid_single
  match "/:section/info" => "front_section#info", :as => :info
  match "/:section/recenzja/:id" => "front_section#review", :as => :front_review

  match 'zmien-jezyk/:locale' => 'application#set_locale', :as => :set_language
  match 'zmien-uzytkownika/:section' => 'admin#set_section', :as => :set_section
  
  get "home/index"

  match "admin" => "admin#index", :as => :admin
  match "admin/login" => "admin#login", :as => :admin_login
  match "admin/enter" => "admin#enter", :as => :admin_enter
  match "admin/logout" => "admin#logout", :as => :admin_logout

  match "galeria/:type" => "galleries#set_gallery_type", :as => :set_gallery_type
  match "sortuj-galerie/:id" => "galleries#sort", :as => :sort_gallery
  resources :galleries
  
  resources :pages

  root :to => 'home#index'
  

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plewiński.com Panel administracyjny</title>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Questrial|Istok+Web&subset=latin,latin-ext" %>
  <%= stylesheet_link_tag "admin", :media => "all" %>
  <%= javascript_include_tag 'jquery.js', 'jquery_ujs.js', 'jquery-ui.js', 'application_jquery.js' %>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag "tiny_mce/tiny_mce.js" %>
  <script type="text/javascript">
    tinyMCE.init({
      mode : "textareas",
      editor_selector : "mceEditor",
      plugins: "media",
      media_strict: false 
    });
  </script>

  <%= yield :javascript %>
</head>
<body>

  <% if alert.present? %>
    <div class="flash-error message" id="error"><span><%= t('error') %></span><br><%= alert %></div>
    <script type="text/javascript">
      $(document).ready(function() {
        $("div.flash-error").delay(5000).slideUp('medium');
      });
    </script>
  <% end %>
  <% if notice.present?  %>
    <div class="flash-notice message" id="notice"><span><%= t('success') %></span><br><%= notice %></div>
    <script type="text/javascript">
      $(document).ready(function() {
        $("div.flash-notice").delay(5000).slideUp('medium');
      });
    </script>
  <% end %>

  <div class="main-wrapper">
    <header><h1>Panel Administracyjny<%= ' - ' if session[:section].present? %><%= display_user(session[:section])%></h1>
      <br><br>
      <% if session[:admin_loggedin] %>
        <%= link_to image_tag('pl.png'), set_language_url(:locale => 'pl'), :class => "#{'lang_selected' if session[:locale] == 'pl'}" %> |
        <%= link_to image_tag('gb.png'), set_language_url(:locale => 'en'), :class => "last-flag #{'lang_selected' if session[:locale] == 'en'}" %>  -
        <% if session[:locale] == 'pl' %>
          Modyfikujesz teraz <strong>Polskie</strong> treści
        <% else %>
          Modyfikujesz teraz <strong>Angielskie</strong> treści
        <% end %>
      <% end %>
    </header>


    <nav class="breadcrumbs">
     <div style="min-width: 290px; float: left;">

       <% if session[:admin_loggedin] %>
         <strong><%= link_to "Wróć do serwisu", root_url, :target => "_blank" %></strong>
         <strong><%= link_to "wyloguj", admin_logout_url %></strong>
       <% end %>
       <span class="next-sep">&nbsp;</span>
     </div>
     <% if session[:admin_loggedin] %>
       <%= link_to display_user(SECTION[0]), set_section_url(:section => SECTION[0]), :class => "#{'selected' if session[:section] == SECTION[0]}" %>
       <%= link_to display_user(SECTION[1]), set_section_url(:section => SECTION[1]), :class => "#{'selected' if session[:section] == SECTION[1]}" %>
       <%= link_to display_user(SECTION[2]), set_section_url(:section => SECTION[2]), :class => "#{'selected' if session[:section] == SECTION[2]}" %>	
     <% end %>
   </nav>
   <div class="admin-content">
     <aside class="main-nav">
       <% if session[:admin_loggedin] %>
         <ul>
           <% if session[:section].present? %>
             <% if session[:section] == SECTION[2] %>
               <% if false %>
                <li><%= link_to "Strony informacyjne", pages_url %></li>
               <% end %>
               <li><%= link_to "Albumy", set_gallery_type_url(:type => GAL_TYPE[0]) %></li>
               <li><%= link_to "Video", vids_url %></li>
             <% else %>
               <li><%= link_to "Strony informacyjne", pages_url %></li>
               <li><%= link_to show_gal_type(session[:section], GAL_TYPE[0]).capitalize, set_gallery_type_url(:type => GAL_TYPE[0]) %></li>
               <li><%= link_to show_gal_type(session[:section], GAL_TYPE[1]).capitalize, set_gallery_type_url(:type => GAL_TYPE[1]) %></li>
             <% end %>
           <% end %>
         </ul>
       <% end %>
     </aside>	

     <div class="page-content">
       <%= yield %>
     </div>
   </div>
   <div class="clear"></div>
 </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= display_user(params[:section]) %> - Plewiński.com - Fotograf</title>
    <meta name=”description” content=”Fotografia Plewiński”>
    <meta name=”keywords” content=”fotograf, fotografia, maciej plewiński, wojciech plewiński, filip plewiński, plewiński autorskie, komercyjne, kraków”>
    <meta name=”robots” content=”index,follow”>
    <%= stylesheet_link_tag "style.css" %>
    <%= stylesheet_link_tag "colorbox.css" %>
    <%= javascript_include_tag "jquery.js" %>
    <%= javascript_include_tag "init.js" %>
    <%= javascript_include_tag "slides.jquery.js" %>
    <%= javascript_include_tag "jquery.colorbox-min.js" %>    
    <%= javascript_include_tag "jquery.nivo.slider.js" %>
            
    
    <script>
      $(function(){
        $("#slides").slides({
         generateNextPrev: true,
         generatePagination: false,
         prev: 'nivo-prevNav',
         next: 'nivo-nextNav'
       });
      });
    </script>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Open+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Voces|Exo:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="main-wrapper">
      <header>
	<div class="languages">
	  <%= link_to image_tag('pl.png'), set_language_url(:locale => 'pl'), :class => "#{'lang_selected' if session[:locale] == 'pl'}" %> |
	  <%= link_to image_tag('gb.png'), set_language_url(:locale => 'en'), :class => "last-flag #{'lang_selected' if session[:locale] == 'en'}" %>
	</div>
	
	<% if params[:controller] == 'home' || params[:action] == 'index' %>
	  <div class="clearspace"></div>
	<% elsif params[:section] == SECTION[2] %>
		<%= link_to image_tag('fillogo.png'), auth_gallery_categories_url, :class => "fil-home" %>
		<%= link_to '', root_url, :class => "home-icon", :style => "display: inline-block;" %>
	<% else %>
	  <h1>
	    
	    <%= link_to display_user(params[:section]), auth_gallery_categories_url %>
	    <%= link_to '', root_url, :class => "home-icon" %>
	  </h1>
	<% end %>
	<% if params[:controller] != 'home' || params[:action] != 'index' %>
  <nav>
    <% if params[:section] == SECTION[2] %>
      <% if session[:locale] == 'pl' %>
      <%= link_to image_tag('pllink1.png'), front_vid_url(:section => params[:section]), :class => "link1" %>
      <%= link_to image_tag('pllink2.png'), auth_gallery_categories_url(:section => params[:section]), :class => "link2" %>
      <% else %>
      <%= link_to image_tag('enlink1.png'), front_vid_url(:section => params[:section]), :class => "link1" %>
      <%= link_to image_tag('enlink2.png'), auth_gallery_categories_url(:section => params[:section]), :class => "link2" %>
      <% end %>
    <% elsif params[:section] == SECTION[0] %>
      <%= link_to t('main.culture'), auth_gallery_categories_url(:section => params[:section]), :class => "#{ set_selected_class("front_section", "auth_gallery") } #{ set_selected_class("front_section", "auth_gallery_categories") }" %>
      <%= link_to t('main.contact'), info_url, :class => "#{ set_selected_class("front_section", ["info","review"]) }" %>
      <%= link_to t('main.nature'), com_gallery_categories_url(:section => params[:section]), :class => "#{ set_selected_class("front_section", "com_gallery") } #{ set_selected_class("front_section", "com_gallery_categories") }" %>
    <% else %>
      <%= link_to t('main.photo_own'), auth_gallery_categories_url(:section => params[:section]), :class => "#{ set_selected_class("front_section", "auth_gallery") } #{ set_selected_class("front_section", "auth_gallery_categories") }" %>
      <%= link_to t('main.contact'), info_url, :class => "#{ set_selected_class("front_section", ["info","review"]) }" %>
      <%= link_to t('main.photo_com'), com_gallery_categories_url(:section => params[:section]), :class => "#{ set_selected_class("front_section", "com_gallery") }" %>
    <% end %>	    
  </nav>
  <div class="clear seperator"></div>
	<% end %>
      </header>

      <%= yield %>
      <div class="clearspace"></div>
    </div>
  </body>
</html>